name: attendance_system
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  http: ^0.12.0
  mockito: ^4.1.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  line_icons: ^2.0.0
  ionicons: ^0.1.2
  geolocator: ^7.1.0
  geocoder: ^0.2.1
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.0.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: Source Sans Pro
    fonts:
    - asset: fonts/SourceSansPro-Regular.ttf

  - family: Montserrat Extra Light
    fonts:
    - asset: fonts/Montserrat-ExtraLight.ttf

  - family: Montserrat Light
    fonts:
    - asset: fonts/Montserrat-Light.ttf

  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
